config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "mini_scheduler/web"

# The following constants have been replaced with `RouteFormat` and are deprecated.
USERNAME_ROUTE_FORMAT = /[%\w.\-]+?/ unless defined?(USERNAME_ROUTE_FORMAT)
BACKUP_ROUTE_FORMAT = /.+\.(sql\.gz|tar\.gz|tgz)/i unless defined?(BACKUP_ROUTE_FORMAT)

Discourse::Application.routes.draw do
  def patch(*)
  end # Disable PATCH requests

  scope path: nil, constraints: { format: %r{(json|html|\*/\*)} } do
    relative_url_root =
      (
        if (
             defined?(Rails.configuration.relative_url_root) &&
               Rails.configuration.relative_url_root
           )
          Rails.configuration.relative_url_root + "/"
        else
          "/"
        end
      )

    match "/404", to: "exceptions#not_found", via: %i[get post]
    get "/404-body" => "exceptions#not_found_body"

    if Rails.env.test? || Rails.env.development?
      get "/bootstrap/plugin-css-for-tests.css" => "bootstrap#plugin_css_for_tests"
      get "/bootstrap/core-css-for-tests.css" => "bootstrap#core_css_for_tests"
    end

    # This is not a valid production route and is causing routing errors to be raised in
    # the test env adding noise to the logs. Just handle it here so we eliminate the noise.
    get "/favicon.ico", to: proc { [200, {}, [""]] } if Rails.env.test?

    post "webhooks/aws" => "webhooks#aws"
    post "webhooks/mailgun" => "webhooks#mailgun"
    post "webhooks/mailjet" => "webhooks#mailjet"
    post "webhooks/mailpace" => "webhooks#mailpace"
    post "webhooks/mandrill" => "webhooks#mandrill"
    get "webhooks/mandrill" => "webhooks#mandrill_head"
    post "webhooks/postmark" => "webhooks#postmark"
    post "webhooks/sendgrid" => "webhooks#sendgrid"
    post "webhooks/sparkpost" => "webhooks#sparkpost"

    scope path: nil, format: true, constraints: { format: :xml } do
      resources :sitemap, only: [:index]
      get "/sitemap_:page" => "sitemap#page", :page => /[1-9][0-9]*/
      get "/sitemap_recent" => "sitemap#recent"
      get "/news" => "sitemap#news"
    end

    scope path: nil, constraints: { format: /.*/ } do
      if Rails.env.development?
        mount Sidekiq::Web => "/sidekiq"
        mount Logster::Web => "/logs"
      else
        # only allow sidekiq in master site
        mount Sidekiq::Web => "/sidekiq", :constraints => AdminConstraint.new(require_master: true)
        mount Logster::Web => "/logs", :constraints => AdminConstraint.new
      end
    end

    resources :about, only: [:index] do
      collection { get "live_post_counts" }
    end

    get "finish-installation" => "finish_installation#index"
    get "finish-installation/register" => "finish_installation#register"
    post "finish-installation/register" => "finish_installation#register"
    get "finish-installation/confirm-email" => "finish_installation#confirm_email"
    put "finish-installation/resend-email" => "finish_installation#resend_email"

    get "pub/check-slug" => "published_pages#check_slug"
    get "pub/by-topic/:topic_id" => "published_pages#details"
    put "pub/by-topic/:topic_id" => "published_pages#upsert"
    delete "pub/by-topic/:topic_id" => "published_pages#destroy"
    get "pub/:slug" => "published_pages#show"

    resources :directory_items, only: [:index]

    get "site" => "site#site"
    namespace :site do
      get "settings"
      get "custom_html"
      get "banner"
      get "emoji"
    end

    get "site/basic-info" => "site#basic_info"
    get "site/statistics" => "site#statistics"

    get "srv/status" => "forums#status"

    get "wizard" => "wizard#index"
    get "wizard/steps/:id" => "wizard#index"
    put "wizard/steps/:id" => "steps#update"

    namespace :admin, constraints: StaffConstraint.new do
      get "" => "admin#index"
      get "search" => "search#index"

      get "plugins" => "plugins#index"
      get "plugins/:plugin_id" => "plugins#show"
      get "plugins/:plugin_id/settings" => "plugins#show"

      resources :site_settings, only: %i[index update], constraints: AdminConstraint.new do
        collection { get "category/:id" => "site_settings#index" }

        put "user_count" => "site_settings#user_count"
      end

      get "reports" => "reports#index"
      get "reports/bulk" => "reports#bulk"
      get "reports/:type" => "reports#show"

      resources :groups, only: [:create] do
        member do
          delete "owners" => "groups#remove_owner"
          put "primary" => "groups#set_primary"
        end
      end
      resources :groups, only: [:destroy], constraints: AdminConstraint.new do
        collection { put "automatic_membership_count" => "groups#automatic_membership_count" }
      end

      resources :users, id: RouteFormat.username, only: %i[index destroy] do
        collection do
          get "list" => "users#index"
          get "list/:query" => "users#index"
          get "ip-info" => "users#ip_info"
          delete "delete-others-with-same-ip" => "users#delete_other_accounts_with_same_ip"
          get "total-others-with-same-ip" => "users#total_other_accounts_with_same_ip"
          put "approve-bulk" => "users#approve_bulk"
          delete "destroy-bulk" => "users#destroy_bulk"
        end
        delete "penalty_history", constraints: AdminConstraint.new
        put "suspend"
        put "delete_posts_batch"
        put "unsuspend"
        put "revoke_admin", constraints: AdminConstraint.new
        put "grant_admin", constraints: AdminConstraint.new
        put "revoke_moderation", constraints: AdminConstraint.new
        put "grant_moderation", constraints: AdminConstraint.new
        put "approve"
        post "log_out", constraints: AdminConstraint.new
        put "activate"
        put "deactivate"
        put "silence"
        put "unsilence"
        put "trust_level"
        put "trust_level_lock"
        put "primary_group"
        post "groups" => "users#add_group", :constraints => AdminConstraint.new
        delete "groups/:group_id" => "users#remove_group", :constraints => AdminConstraint.new
        get "badges"
        get "leader_requirements" => "users#tl3_requirements"
        get "tl3_requirements"
        put "anonymize"
        post "merge"
        post "reset-bounce-score"
        put "disable_second_factor"
        delete "sso_record"
        get "similar-users.json" => "users#similar_users"
        put "delete_associated_accounts"
      end
      get "users/:id.json" => "users#show", :defaults => { format: "json" }
      get "users/:id/:username" => "users#show",
          :constraints => {
            username: RouteFormat.username,
          },
          :as => :user_show
      get "users/:id/:username/badges" => "users#show"
      get "users/:id/:username/tl3_requirements" => "users#show"

      post "users/sync_sso" => "users#sync_sso", :constraints => AdminConstraint.new

      resources :impersonate, only: %i[index create], constraints: AdminConstraint.new

      resources :email, only: [:index], constraints: AdminConstraint.new do
        collection do
          post "test"
          get "sent"
          get "skipped"
          get "bounced"
          get "received"
          get "rejected"
          get "/incoming/:id" => "email#incoming"
          get "/incoming_from_bounced/:id" => "email#incoming_from_bounced"
          get "preview-digest" => "email#preview_digest"
          post "send-digest" => "email#send_digest"
          get "smtp_should_reject"
          post "handle_mail"
          get "advanced-test"
          post "advanced-test" => "email#advanced_test"
          get "templates" => "email_templates#index"
          get "templates/(:id)" => "email_templates#show", :constraints => { id: /[0-9a-z_.]+/ }
          delete "templates/(:id)" => "email_templates#revert",
                 :constraints => {
                   id: /[0-9a-z_.]+/,
                 }
          put "templates/(:id)" => "email_templates#update", :constraints => { id: /[0-9a-z_.]+/ }
        end
      end

      scope "/logs" do
        resources :staff_action_logs, only: [:index]
        get "staff_action_logs/:id/diff" => "staff_action_logs#diff"
        resources :screened_emails, only: %i[index destroy]
        resources :screened_ip_addresses, only: %i[index create update destroy]
        resources :screened_urls, only: [:index]
        resources :search_logs, only: [:index]
        get "search_logs/term/" => "search_logs#term"
      end

      get "/logs" => "staff_action_logs#index"

      # alias
      get "/logs/watched_words", to: redirect(relative_url_root + "admin/customize/watched_words")
      get "/logs/watched_words/*path",
          to: redirect(relative_url_root + "admin/customize/watched_words/%{path}")

      get "customize" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/themes" => "themes#index", :constraints => AdminConstraint.new
      get "customize/components" => "themes#index", :constraints => AdminConstraint.new
      get "customize/theme-components" => "themes#index", :constraints => AdminConstraint.new
      get "customize/colors" => "color_schemes#index", :constraints => AdminConstraint.new
      get "customize/colors/:id" => "color_schemes#index", :constraints => AdminConstraint.new
      get "config/permalinks" => "permalinks#index", :constraints => AdminConstraint.new
      get "customize/embedding" => "embedding#show", :constraints => AdminConstraint.new
      put "customize/embedding" => "embedding#update", :constraints => AdminConstraint.new
      get "customize/embedding/:id" => "embedding#edit", :constraints => AdminConstraint.new

      resources :themes,
                only: %i[index create show update destroy],
                constraints: AdminConstraint.new do
        member do
          get "preview" => "themes#preview"
          get "translations/:locale" => "themes#get_translations"
          put "setting" => "themes#update_single_setting"

app/controllers/exceptions_controller.rb
# frozen_string_literal: true

class ExceptionsController < ApplicationController
  skip_before_action :check_xhr, :preload_json

  def not_found
    # centralize all rendering of 404 into app controller
    raise Discourse::NotFound
  end

  # Give us an endpoint to use for 404 content in the ember app
  def not_found_body
    render html: build_not_found_page(status: 200)
  end
end

app/views/exceptions/_not_found_topics.html.erb
<div class="row page-not-found-topics">
  <% if @top_viewed.count > 0 %>
    <div class="popular-topics">
      <h2 class="popular-topics-title"><%= t 'page_not_found.popular_topics' %></h2>
      <% @top_viewed.each do |t| %>
        <div class='not-found-topic'>
          <%= link_to emoji_codes_to_img(t.fancy_title), t.relative_url %><%= category_badge(t.category) %>
        </div>
      <% end %>
      <a href="<%= path "/top" %>" class="btn btn-default"><%= t 'page_not_found.see_more' %>&hellip;</a>
    </div>
  <% end %>
  <% if @recent.count > 0 %>
    <div class="recent-topics">
      <h2 class="recent-topics-title"><%= t 'page_not_found.recent_topics' %></h2>
      <% @recent.each do |t| %>
        <div class='not-found-topic'>
          <%= link_to t.title, t.relative_url %><%= category_badge(t.category) %>
        </div>
      <% end %>
      <a href="<%= path "/latest" %>" class="btn btn-default"><%= t 'page_not_found.see_more' %>&hellip;</a>
    </div>
  <% end %>
</div>

app/views/exceptions/not_found.html.erb
<% content_for :title do %><%= @page_title %> - <%= SiteSetting.title %><% end %>

<% content_for :head do %>
  <meta id="discourse-error" data-discourse-error="true">
<% end %>

<% content_for :no_ember_head do %>
  <meta id="discourse-error" data-discourse-error="true">
<% end %>

<div class="page-not-found">
  <h1 class="title"><%= @title %></h1>

  <%- if !@current_user %>
    <a href="<%= path "/login" %>" class='btn btn-primary'><%= SvgSprite.raw_svg('user') %><%= I18n.t('log_in') %></a>
  <%- end %>

  <%- if @group&.dig(:allow_membership_requests) %>
    <a href="<%= group_path @group[:name] %>" class='btn btn-primary'><%= SvgSprite.raw_svg('user-plus') %> <%= I18n.t('not_in_group.request_membership') %></a>
  <%- elsif @group&.dig(:public_admission) %>
    <a href="<%= group_path @group[:name] %>" class='btn btn-primary'><%= SvgSprite.raw_svg('user-plus') %> <%= I18n.t('not_in_group.join_group') %></a>
  <%- end %>
</div>

<%= build_plugin_html 'server:not-found-before-topics' %>

<%= @topics_partial %>

<%- unless @hide_search%>
  <div class="row">
    <div class="page-not-found-search">
      <form action='<%= path "/search" %>' id='discourse-search'>
        <label for="search-input"><%= t 'page_not_found.search_title' %></label>
        <input type="text" id="search-input" name="q" value="<%= @slug %>">
        <button class="btn btn-primary"><%= t 'page_not_found.search_button' %></button>
      </form>
    </div>
  </div>

  <%= preload_script('onpopstate-handler') %>
<%- end %>

app/views/exceptions/read_only.html.erb
<p><%= t('read_only_mode_enabled') %></p>